// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw4rk7pTY2NRPew1s-zQU4T5PcdT-iIQo',
    appId: '1:319882213230:web:86db73520e07f9d7e6f37f',
    messagingSenderId: '319882213230',
    projectId: 'agenda-3ee82',
    authDomain: 'agenda-3ee82.firebaseapp.com',
    storageBucket: 'agenda-3ee82.firebasestorage.app',
    measurementId: 'G-JVS9RBCRCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNK0DOFMFtlXfL807bzDLLrkw5stL3JE8',
    appId: '1:319882213230:android:868934c574e67610e6f37f',
    messagingSenderId: '319882213230',
    projectId: 'agenda-3ee82',
    storageBucket: 'agenda-3ee82.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ1grIuU6YBm0Jq7grnAXYZfYKt2IxJ_0',
    appId: '1:319882213230:ios:829e56c968b1b56ae6f37f',
    messagingSenderId: '319882213230',
    projectId: 'agenda-3ee82',
    storageBucket: 'agenda-3ee82.firebasestorage.app',
    iosClientId: '319882213230-1cd80qnarfi2qs1mruhnv732h57blm7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.agenda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ1grIuU6YBm0Jq7grnAXYZfYKt2IxJ_0',
    appId: '1:319882213230:ios:829e56c968b1b56ae6f37f',
    messagingSenderId: '319882213230',
    projectId: 'agenda-3ee82',
    storageBucket: 'agenda-3ee82.firebasestorage.app',
    iosClientId: '319882213230-1cd80qnarfi2qs1mruhnv732h57blm7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.agenda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw4rk7pTY2NRPew1s-zQU4T5PcdT-iIQo',
    appId: '1:319882213230:web:129b7e490ef047a2e6f37f',
    messagingSenderId: '319882213230',
    projectId: 'agenda-3ee82',
    authDomain: 'agenda-3ee82.firebaseapp.com',
    storageBucket: 'agenda-3ee82.firebasestorage.app',
    measurementId: 'G-QS6Q6CE279',
  );
}
